import { MenuConfig, WorkspaceConfig } from '../types';

export const INITIAL_WORKSPACES: WorkspaceConfig[] = [
  {
    id: 'ws-projects',
    name: 'Projects',
    description: 'Track corporate portfolio projects, milestones, budget allocations, and status updates.',
    iconName: 'FolderKanban',
    color: '#0284c7', // Sky Blue
    displayOrder: 1,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-inventory',
    name: 'Inventory & Supplies',
    description: 'Manage warehouse inventory levels, equipment tracking, reorder points, and serial numbers.',
    iconName: 'Boxes',
    color: '#16a34a', // Green
    displayOrder: 2,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-hr',
    name: 'HR & People Operations',
    description: 'Employee onboarding, department rosters, certification status, and training records.',
    iconName: 'Users',
    color: '#9333ea', // Purple
    displayOrder: 3,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-purchase',
    name: 'Procurement & Purchase',
    description: 'Purchase orders, vendor approvals, contract terms, and spend authorization workflows.',
    iconName: 'ShoppingCart',
    color: '#ea580c', // Orange
    displayOrder: 4,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-assets',
    name: 'IT & Fixed Assets',
    description: 'Hardware assignments, software licenses, maintenance schedules, and asset lifecycle.',
    iconName: 'Laptop',
    color: '#2563eb', // Blue
    displayOrder: 5,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'ws-reports',
    name: 'Compliance & Audits',
    description: 'Quarterly compliance checks, internal audit logs, risk assessment, and policy reviews.',
    iconName: 'FileCheck',
    color: '#0d9488', // Teal
    displayOrder: 6,
    visible: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
];

export const INITIAL_MENUS: MenuConfig[] = [
  {
    id: 'menu-active-projects',
    name: 'Active Projects',
    workspaceId: 'ws-projects',
    iconName: 'PlayCircle',
    displayOrder: 1,
    visible: true,
    sharePointSiteId: 'root',
    sharePointListId: 'list-active-projects-id',
    sharePointListName: 'Active Projects List',
    primaryColumn: 'Title',
    descriptionColumn: 'Description',
    visibleColumns: [
      'Title',
      'ProjectImage',
      'ProjectManager',
      'Status',
      'Priority',
      'Budget',
      'StartDate',
      'CompletionPercentage',
      'Department',
      'RiskLevel',
      'ExpectedEndDate',
      'TotalHoursLogged',
      'CostCenter',
      'LeadArchitect',
      'Region',
      'SecurityCompliance',
      'BillingStatus',
      'ClientApproved',
      'ProjectDocURL',
      'Description',
    ],
    defaultSortColumn: 'StartDate',
    defaultSortDirection: 'desc',
    searchColumns: ['Title', 'ProjectManager', 'Status'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: true,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: true, read: true, update: true, delete: false, export: true },
      Employee: { create: false, read: true, update: true, delete: false, export: true },
    },
    pageSize: 10,
  },
  {
    id: 'menu-completed-projects',
    name: 'Completed Projects',
    workspaceId: 'ws-projects',
    iconName: 'CheckCircle2',
    displayOrder: 2,
    visible: true,
    sharePointSiteId: 'root',
    sharePointListId: 'list-completed-projects-id',
    sharePointListName: 'Archived Completed Projects',
    primaryColumn: 'Title',
    descriptionColumn: 'Description',
    visibleColumns: ['Title', 'ProjectManager', 'Budget', 'CompletionDate', 'ClientRating'],
    defaultSortColumn: 'CompletionDate',
    defaultSortDirection: 'desc',
    searchColumns: ['Title', 'ProjectManager'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: true,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: false, read: true, update: false, delete: false, export: true },
      Employee: { create: false, read: true, update: false, delete: false, export: true },
    },
    pageSize: 10,
  },
  {
    id: 'menu-warehouse-stock',
    name: 'Warehouse Stock',
    workspaceId: 'ws-inventory',
    iconName: 'Package',
    displayOrder: 1,
    visible: true,
    sharePointSiteId: 'root',
    sharePointListId: 'list-warehouse-stock-id',
    sharePointListName: 'Central Inventory Stock List',
    primaryColumn: 'SKU',
    descriptionColumn: 'ItemName',
    visibleColumns: ['SKU', 'ItemName', 'Category', 'QuantityInStock', 'ReorderPoint', 'UnitPrice', 'WarehouseLocation'],
    defaultSortColumn: 'QuantityInStock',
    defaultSortDirection: 'asc',
    searchColumns: ['SKU', 'ItemName', 'Category', 'WarehouseLocation'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: true,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: true, read: true, update: true, delete: true, export: true },
      Employee: { create: true, read: true, update: true, delete: false, export: true },
    },
    pageSize: 10,
  },
  {
    id: 'menu-employee-directory',
    name: 'Employee Directory',
    workspaceId: 'ws-hr',
    iconName: 'UserCheck',
    displayOrder: 1,
    visible: true,
    sharePointSiteId: 'root',
    sharePointListId: 'list-employee-directory-id',
    sharePointListName: 'Employee Profiles',
    primaryColumn: 'FullName',
    descriptionColumn: 'JobTitle',
    visibleColumns: ['FullName', 'EmployeeID', 'Department', 'JobTitle', 'Email', 'HireDate', 'EmploymentStatus'],
    defaultSortColumn: 'FullName',
    defaultSortDirection: 'asc',
    searchColumns: ['FullName', 'EmployeeID', 'Department', 'JobTitle'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: false,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: true, read: true, update: true, delete: false, export: true },
      Employee: { create: false, read: true, update: false, delete: false, export: true },
    },
    pageSize: 10,
  },
  {
    id: 'menu-purchase-orders',
    name: 'Purchase Orders',
    workspaceId: 'ws-purchase',
    iconName: 'FileText',
    displayOrder: 1,
    visible: true,
    sharePointSiteId: 'root',
    sharePointListId: 'list-purchase-orders-id',
    sharePointListName: 'Vendor Purchase Requests',
    primaryColumn: 'PONumber',
    descriptionColumn: 'VendorName',
    visibleColumns: ['PONumber', 'VendorName', 'TotalAmount', 'ApprovalStatus', 'RequestedBy', 'RequiredDate'],
    defaultSortColumn: 'RequiredDate',
    defaultSortDirection: 'desc',
    searchColumns: ['PONumber', 'VendorName', 'ApprovalStatus'],
    allowSearch: true,
    allowFilter: true,
    allowExport: true,
    allowFileUpload: true,
    permissions: {
      Administrator: { create: true, read: true, update: true, delete: true, export: true },
      Manager: { create: true, read: true, update: true, delete: false, export: true },
      Employee: { create: true, read: true, update: false, delete: false, export: true },
    },
    pageSize: 10,
  },
];
